### ISSUE TITLE
Can exclude those that do not contain Japanese (or any language) fonts

### ISSUE THREAD

**Issue by NaokiSato102** [ssssota/fontvuer#52]
日本語フォントが含まれない英字フォントを除外して日本語フォント検索を簡単に出来ると嬉しいです。

たぶんこれを実装すると、ほかの言語での縛りも可能になると思われますので、
メイン画面から以下のようにチェックボックスで表示設定を変えれるようにしてほしいです。
- [ ] 日本語
- [ ] English
- [ ] 中国語
etc...

**Comment by ssssota** [comment]
かなり難しそうな機能ですね。
一番最初に思いついた実装方法としてはファミリ名が日本語であれば…といった形でしょうか。不正確にはなると思いますが。
なにかいい方法があれば教えていただけたらと思います。思いつくまで保留になりそう。

**Comment by ssssota** [comment]
`fontkit`などを用い対応言語の取得を試みましたが、「何をそのファイルの対応言語とするか」の定義が大変難しいためこちらのIssueは一度Closeさせていただきます。

代わりといってはなんですが、#55 にて対応フォントのみ表示するオプションの実装を進めたいと考えています。
