### ISSUE TITLE
機能要望：バージョン確認機能の追加。もしくはすでにあるならそれのアクセス性の向上

### ISSUE THREAD

**Issue by NaokiSato102** [ssssota/fontvuer#57]
バージョン確認機能の追加。もしくはすでにあるならそれのアクセス性の向上を求めます。
よくあるヘルプとか、「○○について（○○にはアプリ名）」とかのタブでアクセスできるようにしていただけるとありがたいです。そういえば新しいバージョン出てるかなーと思って確認しようとしましたが、そもそも現行が何Verかわからないと更新する必要があるのかないのかもわからないです。

**Comment by ssssota** [comment]
version 1.0.4にてバージョン表示を設定内に追加しました。
fontvuer起動時にアップデート情報が表示されることともにご確認ください。

**Comment by NaokiSato102** [comment]
アップデート告知を見る前に更新を入れてしまったので確認できませんでした。
