### ISSUE TITLE
機能要望：新バージョン告知機能および可能であれば自動アップデート

### ISSUE THREAD

**Issue by NaokiSato102** [ssssota/fontvuer#58]
タイトル通りです。よろしくお願いいたします。

**Comment by ssssota** [comment]
新バージョンの通知機能についてはすでに搭載されているはずです。
自動アップデートについては、技術的制約のため優先順位が低めにはなります。

**Comment by ssssota** [comment]
自動アップデートについて思い出したので補足します。
技術的制約というよりは、Apple Developer Programを利用しコード署名を行う必要があるため現在は視野に入れていないです。
（無料で実現できない）

**Comment by NaokiSato102** [comment]
了解です。issue閉じます
