### ISSUE TITLE
monospace option please

### ISSUE THREAD

**Issue by sassbalint** [ssssota/fontvuer#6]
__Could you please include an option to select only `monospace`-capable fonts?__

I imagine an `M` button next to `I` (_italic_). And a `Ctrl+M` shortcut. :)

(I guess, the info whether a font has `monospace` support or not is available for you.
Clicking a font, this info is shown at the bottom.)

`fontvuer` is [the best font viewer](https://unix.stackexchange.com/a/594247/406868) I have ever seen. Keep up the good work!

Thank you! :)

**Comment by ssssota** [comment]
Thank you for your issue.
And, I'm glad to your comments.

I'm gonna add this feature.

**Comment by sassbalint** [comment]
> I'm gonna add this feature.

Great! :smiley:

**Comment by ssssota** [comment]
🎉Released!

[v0.4.0](https://github.com/ssssota/fontvuer/releases/tag/v0.4.0)

**Comment by sassbalint** [comment]
Thank you! In two days... Respect!

**Comment by sassbalint** [comment]
Installation `snap refresh` works smoothly. :heavy_check_mark:

**Comment by sassbalint** [comment]
For me, `Ctrl-m` is _not working._
`Ctrl-i` is working.
Clicking `m` is working.

**Comment by sassbalint** [comment]
Khm.. I am very sorry, I see now, that my request was not clear enough.

I would like to __see__ the monospace version of fonts.
This would allow me to choose a suitable monospace font for my documents which is the goal.

Now, if I am not wrong, after clicking `m` only fonts which have monospace capatibility are there (this works great!),
but you display the sample text using original regular font, not the monospace version.

The method I imagined was exactly how _italic_ works in `fontvuer`:
1. if the font does not have monospace: _a warning should be shown;_
2. it the font have monospace: the sample text _should be shown in monospace._ 

I am grateful to have 0.4.0, thank you, but...
...what do you think about the above? :)

Maybe it would be good to have a line about monospace as well in _Settings_,
and also a _"Don't display fonts that has no monospace"_ option in _More settings._

It would be another big plus if you could pay attention to handling _the combination of `m` and `i`._)

Think that nothing is enough for me? You are right. :)

**Comment by ssssota** [comment]
OMG!

I reopened this issue.

I understood.
I try fix monospace feature.

I'm sorry.

**Comment by ssssota** [comment]
Maybe I did it.

But, you can see fonts not monospace, if you enable monospace option.
Fontvuer is depend on [font-manager](https://github.com/foliojs/font-manager).
font-manager gets some incorrect data.

**Comment by ssssota** [comment]
if you can build, please check #13 .
if you can't, I will merge it. and release

**Comment by sassbalint** [comment]
> if you can build, please check #13 .
> if you can't, I will merge it. and release

Sorry, I tried to build `fontvuer` few days ago without success.
So please release the new version and I will update mine using `snap`.

Thank you! :)

**Comment by ssssota** [comment]
🎉 Released!

[0.5.0](https://github.com/ssssota/fontvuer/releases/tag/v0.5.0)

**Comment by ssssota** [comment]
@sassbalint 
Please update and check changes.
If you think no problem, close this issue.
If you don't think, please tell me problem.

**Comment by ssssota** [comment]
Maybe resolved
