### ISSUE TITLE
Windowsディフェンダーによって警告が出る

### ISSUE THREAD

**Issue by NaokiSato102** [ssssota/fontvuer#70]
1.0.4Setup実行時に警告が出る。無視してインストールは可能であるが、知識がない人の場合これが誤認と分からないので対応を願う。

**Comment by ssssota** [comment]
把握しております。
#58 と同様ですが、警告を消すためにはコード署名が必要で、これには学生としてはそれなりに高い額を要します。
したがって、fontvuer本体として直近対応するつもりはありません。
ホームページに、そのような旨を追記するのは考えます。

**Comment by ssssota** [comment]
[私の以前のツイート](https://twitter.com/ssssotaro/status/1278875348302614528)

> 署名、1年で数万するな
> Donate募らないと無理というか、許して

**Comment by NaokiSato102** [comment]
了解です
