### ISSUE TITLE
your english is wrong

### ISSUE THREAD

**Issue by aum7** [ssssota/fontvuer#97]
olo
thx for sharing
text:
This is a cross platform fontviewer. You can preview fonts that installed.
correct text:
This is a cross platform fontviewer. You can preview fonts that are installed.
text:
You can see in [screenshots]

not really wrong text, but is somehow not correct
correct text:
You can see [screenshots]
or
you can check screenshots
also the screenshots link is dead / not working / gives error 404
------
webpage:
https://fontvuer.netlify.app/

[logo] fontvuer
[Download](https://fontvuer.netlify.app/#download)
You can [choice] choose a font.

You can change the styles.
[DOWNLOAD](https://fontvuer.netlify.app/#download)
Listed fonts

This software [list] lists all fonts that [is] are installed [in] on your computer. {is - singular, one font; are - plural, more than one, many fonts}
Change text

You can [look for] check a font with your [hope] own text.
Change styles

You can change font styles.

    Font weight
    Font styles(Italic..)

Screenshots

Screenshots is [here] {this link is also not working / dead / gives error 404}
Download
Windows

[fontvuer-Setup-1.0.4.exe]
macOS

[fontvuer-1.0.4.dmg]
Linux

[fontvuer-1.0.4.AppImage]

[or Download with Snap]

[Other versions.]
This software is Open Source

You can customize [] it.

Please contribute [] to the development [for] of "fontvuer" if you can.

Repository is [here.]
------------------
have fun
aum
s love nia

**Comment by Phroneris** [comment]
@aum7
Creating a pull request to https://github.com/ssssota/fontvuer-pr seems better.

@ssssota
サイトを開いて一発目のデカい "You can choice a font." がもう間違っているので（choiceは名詞です）、多分英語的にかなり奇妙なサイトになってしまっていることが懸念されます…

**Comment by ssssota** [comment]
@aum7 
Thank you for pointing this out.
I'm sorry for not noticing this issue,
I will consider closing the website itself as this project is already not well managed.
Thank you again for pointing out this minor project.

@Phroneris 
ご指摘ありがとうございます。
コメントいただけるまでこのissueに気づいてすらいませんでした。
学生時代に作ったものが今なお誰かに見られていることがわかり嬉しくもあり申し訳なくもあり恥ずかしい思いです。
このようなマイナーなプロジェクトの1 issueにコメント下さり重ね重ね感謝申し上げます。

**Comment by ssssota** [comment]
https://fontvuer.netlify.app/ has been closed!

**Comment by Phroneris** [comment]
お疲れ様でした。
このリポジトリや関連リポジトリはArchiveするのがよろしいかと思います
